// Generated by Wrangler on Sun Mar 10 2024 09:18:30 GMT+0700 (Western Indonesia Time)
// by running `wrangler types`

interface Env {
	THE_MOVIE_DB_ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MTZlOGVhODUzODE5YjZjZDkwZGFjMWQyMWZmY2U4OSIsInN1YiI6IjViZjdlYjMxMGUwYTI2NDMyMDA1NmQ5YiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Nzk85iuWIOoJXcT0feUUy8LX9p7YeWLZHQIowueJRPE";
}
